### ISSUE TITLE
Utilizing data in charts?

### ISSUE THREAD

**Issue by awra2001** [DeLuca21/ynab-ha#2]
Hi there:

First, I love this new addition, and much easier than when I had to run the API myself.

My question is that when I try to use the sensors in a way that would allow me to visualize, I cannot get any of the varying cards (ApexCharts, Bar-Card, etc) to draw it up.  My presumption is that it's an issue of requiring it to be in a currency.

I don't know what you may be using to stack spent and budgeted, but I'm all ears.

Thanks!

**Comment by DeLuca21** [comment]
I didn't even think about using charts to display historical data as I intended to use only for a quick look of the balances, activity numbers etc. as well as automations with lights depending on balances or using TTS to hear something like "You have $200 available for groceries" based on the usual day/times I would do shopping.

I don't think the currency has anything to do with it, as the currency should just be the "unit" and not have anything to do with the float.

I have tested with Apex Charts and can get a nice line graph of the sensors states, but for the attributes I am only able to get the last data point, (unless you want create template sensors for the attributes) below example of just a sensor.

``` yaml

type: custom:apexcharts-card
header:
  title: Checking Account
graph_span: 1d
series:
  - entity: sensor.test_checking_account_ynab_test_account
    type: line
yaxis:
  - min: 0
    max: ~100
    decimals: 0
    apex_config:
      tickAmount: 4

````

![Image](https://github.com/user-attachments/assets/4a53d508-50f1-4a5d-bd93-42bb581c19ee)


However using Mini Graph Card, I can pull the attributes directly with the below. Attached screenshot shows (Top) getting accounts sensors directly, (Middle & Bottom) getting attributes from a category sensor.

The lines are a bit sparse as this is a test account on YNAB with not much data.
Give the Mini Graph Card a try and let me know if you can visualise your data how you would like to.


``` yaml

type: custom:mini-graph-card
name: Test Graphs (Budgeted)
hours_to_show: 24
animate: true
show:
  labels: true
  points: false
entities:
  - entity: sensor.entertainment_ynab_test_account
    attribute: budgeted
    name: Entertainment
  - entity: sensor.groceries_ynab_test_account
    attribute: budgeted
    name: Groceries
  - entity: sensor.transportation_ynab_test_account
    attribute: budgeted
    name: Fuel

```
![Image](https://github.com/user-attachments/assets/2bebb164-a855-4393-91ee-155f9097fecc)
